//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressType
    {
        public AddressType()
        {
            this.ContactAddresses = new HashSet<ContactAddress>();
        }
    
        public short AddressTypeId { get; set; }
        public string AddressTypeName { get; set; }
    
        public virtual ICollection<ContactAddress> ContactAddresses { get; set; }
    }
}
