//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adon
    {
        public Adon()
        {
            this.ProductAdons = new HashSet<ProductAdon>();
        }
    
        public short AdOnID { get; set; }
        public string AdOnName { get; set; }
        public short AdonType { get; set; }
        public string ImageName { get; set; }
    
        public virtual AdonType AdonType1 { get; set; }
        public virtual ICollection<ProductAdon> ProductAdons { get; set; }
    }
}
