//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdOnTypeInProduct
    {
        public AdOnTypeInProduct()
        {
            this.ProductAdons = new HashSet<ProductAdon>();
        }
    
        public long ProductsAdOnTypeId { get; set; }
        public long BrachProductID { get; set; }
        public short AdonTypeID { get; set; }
        public bool Enable { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> DisplayFormat { get; set; }
    
        public virtual AdonType AdonType { get; set; }
        public virtual ProductsInBranch ProductsInBranch { get; set; }
        public virtual ICollection<ProductAdon> ProductAdons { get; set; }
    }
}
