//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdonType
    {
        public AdonType()
        {
            this.Adons = new HashSet<Adon>();
            this.AdOnTypeInProducts = new HashSet<AdOnTypeInProduct>();
        }
    
        public short AdOnTypeId { get; set; }
        public string AdOnTypeName { get; set; }
        public bool IsFreeAdonType { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<Adon> Adons { get; set; }
        public virtual ICollection<AdOnTypeInProduct> AdOnTypeInProducts { get; set; }
    }
}
