//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.BranchDeliveryAreas = new HashSet<BranchDeliveryArea>();
            this.ProductsInBranches = new HashSet<ProductsInBranch>();
        }
    
        public int BranchID { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public System.DateTime WorkingHourStart { get; set; }
        public System.DateTime WorkingHourEnd { get; set; }
        public decimal TaxPercentage { get; set; }
        public bool IsDeliveryEnabled { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsClose { get; set; }
    
        public virtual ICollection<BranchDeliveryArea> BranchDeliveryAreas { get; set; }
        public virtual ICollection<ProductsInBranch> ProductsInBranches { get; set; }
    }
}
