//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public ContactInfo()
        {
            this.ContactAddresses = new HashSet<ContactAddress>();
            this.Orders = new HashSet<Order>();
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public long ContactInfoId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<ContactAddress> ContactAddresses { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
