//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionTypesInProduct
    {
        public OptionTypesInProduct()
        {
            this.ProductOptionsInProducts = new HashSet<ProductOptionsInProduct>();
        }
    
        public long ProductsOptionTypeId { get; set; }
        public short OptionTypeID { get; set; }
        public long BranchProductID { get; set; }
        public bool IsMultiSelect { get; set; }
        public bool IsSamePrice { get; set; }
        public bool IsAdonPriceVary { get; set; }
        public bool IsProductPriceChangeType { get; set; }
    
        public virtual OptionType OptionType { get; set; }
        public virtual ProductsInBranch ProductsInBranch { get; set; }
        public virtual ICollection<ProductOptionsInProduct> ProductOptionsInProducts { get; set; }
    }
}
