//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public long ContactInfoId { get; set; }
        public int OrderStatusID { get; set; }
        public int BranchID { get; set; }
        public double OrderTotal { get; set; }
        public Nullable<double> DeliveryCharges { get; set; }
        public string DeliveryAddress { get; set; }
        public short OrderTypeID { get; set; }
        public Nullable<double> Discount { get; set; }
        public double TaxPercentage { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<short> PaymentMethod { get; set; }
        public Nullable<int> PromotionCodeId { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderType OrderType { get; set; }
    }
}
