//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailAdOn
    {
        public long OrderDetailAdonId { get; set; }
        public long OrderDetailId { get; set; }
        public short AdOnId { get; set; }
        public string AdonName { get; set; }
        public short SelectedAdonOption { get; set; }
        public bool IsDoubleSelected { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
