//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailSubProductAdon
    {
        public int OrderDetailSubProductAdonId { get; set; }
        public int OrderDetailSubProductId { get; set; }
        public short AdOnId { get; set; }
        public string AdonName { get; set; }
        public short SelectedAdonOption { get; set; }
        public bool IsDoubleSelected { get; set; }
        public double Price { get; set; }
    }
}
