//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.OrderDetailAdOns = new HashSet<OrderDetailAdOn>();
            this.OrderDetailOptions = new HashSet<OrderDetailOption>();
            this.OrderDetailSubProducts = new HashSet<OrderDetailSubProduct>();
        }
    
        public long OrderDetailID { get; set; }
        public long OrderID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public Nullable<int> ParentProductId { get; set; }
        public string RecipientName { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsGroupProduct { get; set; }
        public string Crust { get; set; }
    
        public virtual ICollection<OrderDetailAdOn> OrderDetailAdOns { get; set; }
        public virtual ICollection<OrderDetailOption> OrderDetailOptions { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderDetailSubProduct> OrderDetailSubProducts { get; set; }
    }
}
