//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public short CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> DisplayOnHomePage { get; set; }
        public Nullable<bool> WebCategory { get; set; }
        public Nullable<bool> DesktopCategory { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
