//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductChildProductOption
    {
        public int ProductChildProductOptionId { get; set; }
        public int ComboId { get; set; }
        public int OptionId { get; set; }
        public double Price { get; set; }
    }
}
