//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsChildRelationship
    {
        public int ComboId { get; set; }
        public int ParentProductsId { get; set; }
        public int ChildProductId { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<short> NumberOfFreeTopping { get; set; }
        public bool IsCustomizable { get; set; }
    }
}
