//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAdon
    {
        public long ProductAdOnID { get; set; }
        public long ProductAdonTypeID { get; set; }
        public short AdonID { get; set; }
        public short DefaultSelected { get; set; }
        public bool Enable { get; set; }
    
        public virtual Adon Adon { get; set; }
        public virtual AdOnTypeInProduct AdOnTypeInProduct { get; set; }
    }
}
