//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOption
    {
        public ProductOption()
        {
            this.ProductOptionsInProducts = new HashSet<ProductOptionsInProduct>();
        }
    
        public int OptionID { get; set; }
        public string OptionName { get; set; }
        public short OptionTypeId { get; set; }
    
        public virtual OptionType OptionType { get; set; }
        public virtual ICollection<ProductOptionsInProduct> ProductOptionsInProducts { get; set; }
    }
}
