//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsInBranch
    {
        public ProductsInBranch()
        {
            this.AdOnTypeInProducts = new HashSet<AdOnTypeInProduct>();
            this.OptionTypesInProducts = new HashSet<OptionTypesInProduct>();
        }
    
        public long BranchProductID { get; set; }
        public int ProductID { get; set; }
        public int BranchID { get; set; }
        public bool Enable { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> AddToCheckOut { get; set; }
        public Nullable<double> CheckOutPrice { get; set; }
    
        public virtual ICollection<AdOnTypeInProduct> AdOnTypeInProducts { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<OptionTypesInProduct> OptionTypesInProducts { get; set; }
        public virtual Product Product { get; set; }
    }
}
