//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginType
    {
        public UserLoginType()
        {
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public short LoginTypeId { get; set; }
        public string LoginTypeName { get; set; }
    
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
