//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public long UserLoginId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Enable { get; set; }
        public long ContactInfoId { get; set; }
        public short UserTypeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual UserLoginType UserLoginType { get; set; }
    }
}
